import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <head>
          <style>{`
            .cl-internal-1dauvpw, .cl-internal-1hp5nqm , .selection-tag, .number-of-selection{
              display: none !important;
            }
            html body .cl-internal-1dauvpw , .cl-internal-1hp5nqm{
              display: none !important;
            }
            .cl-rootBox .cl-card .cl-internal-1dauvpw {
              display: none !important;
            }
            .correct, .incorrect{
            background:green !important;
            }
          `}</style>
        </head>
        <body className={inter.className}>{children}</body>
      </html>
    </ClerkProvider>
  );
}
